import { NextResponse } from "next/server";
import { z } from "zod";
import { withAuth, roleGuards } from "@/lib/auth/require-role";
import { createAdminClient } from "@/lib/supabase/admin";

const notificationKeys = [
  "newIncidentsReported",
  "aiEvaluationComplete",
  "documentApproved",
  "meetingScheduled",
  "documentAwaitingSignature",
  "documentSigned",
  "disputeSubmitted",
  "aiBudgetAlerts",
  "meetingReminder24h",
  "signatureReminder72h",
] as const;

const notificationSchema = z.object(
  Object.fromEntries(notificationKeys.map((key) => [key, z.boolean()])) as Record<
    (typeof notificationKeys)[number],
    z.ZodBoolean
  >,
);

const patchSchema = z
  .object({
    company: z
      .object({
        name: z.string().trim().min(1).max(255),
        industry: z.string().trim().max(100),
        size: z.string().trim().max(50),
        country: z.string().trim().max(2),
      })
      .optional(),
    notifications: notificationSchema.optional(),
    security: z
      .object({
        microsoftSso: z.boolean(),
        googleSso: z.boolean(),
        emailPassword: z.boolean(),
      })
      .optional(),
    ai: z
      .object({
        confidenceThreshold: z.number().min(50).max(99),
        autoGenerateDocuments: z.boolean(),
        allowDisputes: z.boolean(),
        aiMeetingSummaries: z.boolean(),
        monthlyBudgetUsd: z.number().min(0).max(100000),
      })
      .optional(),
  })
  .refine((value) => Boolean(value.company || value.notifications || value.security || value.ai), {
    message: "At least one settings section is required",
  });

function getDefaultNotifications() {
  return {
    newIncidentsReported: true,
    aiEvaluationComplete: true,
    documentApproved: true,
    meetingScheduled: true,
    documentAwaitingSignature: true,
    documentSigned: true,
    disputeSubmitted: true,
    aiBudgetAlerts: true,
    meetingReminder24h: true,
    signatureReminder72h: true,
  };
}

function mapSettings(company: {
  name: string;
  industry: string | null;
  size: string | null;
  country: string | null;
  ai_confidence_threshold: number | string | null;
  settings: Record<string, unknown> | null;
}) {
  const settings = (company.settings as Record<string, unknown> | null) ?? {};
  const featureFlags = (settings.feature_flags as Record<string, unknown> | undefined) ?? {};
  const notificationPrefs =
    (settings.notification_prefs as Record<string, unknown> | undefined) ?? {};
  const defaults = getDefaultNotifications();

  return {
    company: {
      name: company.name,
      industry: company.industry ?? "",
      size: company.size ?? "",
      country: company.country ?? "US",
    },
    notifications: Object.fromEntries(
      Object.entries(defaults).map(([key, defaultValue]) => [
        key,
        typeof notificationPrefs[key] === "boolean" ? notificationPrefs[key] : defaultValue,
      ]),
    ) as Record<string, boolean>,
    security: {
      microsoftSso: Boolean(featureFlags.microsoft_sso),
      googleSso: featureFlags.google_sso === undefined ? true : Boolean(featureFlags.google_sso),
      emailPassword:
        featureFlags.email_password === undefined ? true : Boolean(featureFlags.email_password),
    },
    ai: {
      confidenceThreshold: Math.round(Number(company.ai_confidence_threshold ?? 0.9) * 100),
      autoGenerateDocuments: Boolean(featureFlags.ai_auto_generate),
      allowDisputes:
        featureFlags.employee_dispute === undefined
          ? true
          : Boolean(featureFlags.employee_dispute),
      aiMeetingSummaries: Boolean(featureFlags.ai_meeting_summary),
      monthlyBudgetUsd: Number(settings.ai_monthly_budget_usd ?? 50),
    },
  };
}

export const GET = withAuth(async (_request, _context, { user }) => {
  try {
    const admin = createAdminClient();
    const { data: company, error } = await admin
      .from("companies")
      .select("name, industry, size, country, ai_confidence_threshold, settings")
      .eq("id", user.companyId)
      .single();

    if (error || !company) {
      console.error("[settings:get] Failed:", error);
      return NextResponse.json({ error: "Failed to load settings" }, { status: 500 });
    }

    return NextResponse.json(mapSettings(company));
  } catch (error) {
    console.error("[settings:get] Failed:", error);
    return NextResponse.json({ error: "Failed to load settings" }, { status: 500 });
  }
});

export const PATCH = withAuth(
  { roles: roleGuards.companyAdminOnly },
  async (request, _context, { user }) => {
    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
    }

    const parsed = patchSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        {
          error: parsed.error.issues[0]?.message ?? "Validation failed",
          details: parsed.error.issues.map((issue) => ({
            field: issue.path.join("."),
            message: issue.message,
          })),
        },
        { status: 400 },
      );
    }

    try {
      const admin = createAdminClient();
      const { data: currentCompany, error: currentError } = await admin
        .from("companies")
        .select("name, industry, size, country, ai_confidence_threshold, settings")
        .eq("id", user.companyId)
        .single();

      if (currentError || !currentCompany) {
        console.error("[settings:update] Failed to load current company:", currentError);
        return NextResponse.json({ error: "Failed to load settings" }, { status: 500 });
      }

      const currentSettings = (currentCompany.settings as Record<string, unknown> | null) ?? {};
      const currentFeatureFlags =
        (currentSettings.feature_flags as Record<string, unknown> | undefined) ?? {};
      const nextSettings: Record<string, unknown> = { ...currentSettings };
      const nextFeatureFlags: Record<string, unknown> = { ...currentFeatureFlags };
      const updates: Record<string, unknown> = {};

      if (parsed.data.company) {
        updates.name = parsed.data.company.name;
        updates.industry = parsed.data.company.industry || null;
        updates.size = parsed.data.company.size || null;
        updates.country = parsed.data.company.country || null;
      }

      if (parsed.data.notifications) {
        nextSettings.notification_prefs = parsed.data.notifications;
      }

      if (parsed.data.security) {
        nextFeatureFlags.microsoft_sso = parsed.data.security.microsoftSso;
        nextFeatureFlags.google_sso = parsed.data.security.googleSso;
        nextFeatureFlags.email_password = parsed.data.security.emailPassword;
      }

      if (parsed.data.ai) {
        updates.ai_confidence_threshold = parsed.data.ai.confidenceThreshold / 100;
        nextFeatureFlags.ai_auto_generate = parsed.data.ai.autoGenerateDocuments;
        nextFeatureFlags.employee_dispute = parsed.data.ai.allowDisputes;
        nextFeatureFlags.ai_meeting_summary = parsed.data.ai.aiMeetingSummaries;
        nextSettings.ai_monthly_budget_usd = parsed.data.ai.monthlyBudgetUsd;
        nextSettings.ai = {
          confidenceThreshold: parsed.data.ai.confidenceThreshold,
          allowDisputes: parsed.data.ai.allowDisputes,
          autoGenerateDocuments: parsed.data.ai.autoGenerateDocuments,
          aiMeetingSummaries: parsed.data.ai.aiMeetingSummaries,
          monthlyBudgetUsd: parsed.data.ai.monthlyBudgetUsd,
        };
      }

      nextSettings.feature_flags = nextFeatureFlags;
      updates.settings = nextSettings;

      const { data: updatedCompany, error: updateError } = await admin
        .from("companies")
        .update(updates)
        .eq("id", user.companyId)
        .select("name, industry, size, country, ai_confidence_threshold, settings")
        .single();

      if (updateError || !updatedCompany) {
        console.error("[settings:update] Failed:", updateError);
        return NextResponse.json({ error: "Failed to update settings" }, { status: 500 });
      }

      return NextResponse.json(mapSettings(updatedCompany));
    } catch (error) {
      console.error("[settings:update] Failed:", error);
      return NextResponse.json({ error: "Failed to update settings" }, { status: 500 });
    }
  },
);