/**
 * Zod validation schemas for the 5-step company onboarding wizard.
 *
 * Each step has its own schema for per-step validation, plus a combined
 * schema used when submitting the full wizard payload to the API.
 */
import { z } from "zod";

// ---------------------------------------------------------------------------
// Step 1: Company Info
// ---------------------------------------------------------------------------

export const INDUSTRY_OPTIONS = [
  "Technology",
  "Healthcare",
  "Finance",
  "Retail",
  "Manufacturing",
  "Other",
] as const;

export const COMPANY_SIZE_OPTIONS = [
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "500+",
] as const;

/**
 * Common country list (subset for MVP — can be expanded later).
 * Values are ISO 3166-1 alpha-2 codes.
 */
export const COUNTRY_OPTIONS = [
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "GB", label: "United Kingdom" },
  { value: "AU", label: "Australia" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "IN", label: "India" },
  { value: "JP", label: "Japan" },
  { value: "BR", label: "Brazil" },
  { value: "MX", label: "Mexico" },
  { value: "NG", label: "Nigeria" },
  { value: "KE", label: "Kenya" },
  { value: "ZA", label: "South Africa" },
  { value: "SG", label: "Singapore" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "OTHER", label: "Other" },
] as const;

export const companyInfoSchema = z.object({
  name: z
    .string()
    .min(2, "Company name must be at least 2 characters")
    .max(255, "Company name must be at most 255 characters"),
  industry: z.enum(INDUSTRY_OPTIONS, {
    message: "Please select an industry",
  }),
  size: z.enum(COMPANY_SIZE_OPTIONS, {
    message: "Please select a company size",
  }),
  country: z.string().min(1, "Please select a country"),
  region: z
    .string()
    .min(1, "Region/State is required")
    .max(255, "Region must be at most 255 characters"),
});

export type CompanyInfo = z.infer<typeof companyInfoSchema>;

// ---------------------------------------------------------------------------
// Step 2: Invite Team
// ---------------------------------------------------------------------------

export const INVITE_ROLE_OPTIONS = ["HR_AGENT", "MANAGER"] as const;
export type InviteRole = (typeof INVITE_ROLE_OPTIONS)[number];

export const teamInviteSchema = z.object({
  email: z
    .string()
    .min(1, "Email is required")
    .email("Please enter a valid email address"),
  role: z.enum(INVITE_ROLE_OPTIONS, {
    message: "Please select a role",
  }),
});

export type TeamInvite = z.infer<typeof teamInviteSchema>;

export const inviteListSchema = z.array(teamInviteSchema).optional().default([]);

// ---------------------------------------------------------------------------
// Step 3: Configure Policies
// ---------------------------------------------------------------------------

/**
 * AI policy template identifiers.
 * These correspond to seeded template records.
 */
export const POLICY_TEMPLATES = [
  {
    id: "attendance-punctuality",
    title: "Attendance & Punctuality Policy",
    description:
      "Covers tardiness, unexcused absences, and attendance tracking. The AI will monitor patterns and flag violations based on your configured threshold.",
  },
  {
    id: "workplace-conduct",
    title: "Workplace Conduct Policy",
    description:
      "Covers insubordination, harassment, inappropriate behavior, and professional conduct standards. The AI will analyze incident reports and recommend actions.",
  },
  {
    id: "performance-management",
    title: "Performance Management Policy",
    description:
      "Covers poor performance, missed deadlines, and quality standards. The AI will track performance metrics and suggest progressive discipline steps.",
  },
] as const;

export type PolicyTemplateId = (typeof POLICY_TEMPLATES)[number]["id"];

export const policySelectionSchema = z
  .array(z.string())
  .min(1, "Please select at least one policy template");

// ---------------------------------------------------------------------------
// Step 4: AI Settings
// ---------------------------------------------------------------------------

export const aiSettingsSchema = z.object({
  confidenceThreshold: z
    .number()
    .min(50, "Threshold must be at least 50%")
    .max(99, "Threshold must be at most 99%"),
  allowDisputes: z.boolean(),
  autoGenerateDocuments: z.boolean(),
});

export type AISettings = z.infer<typeof aiSettingsSchema>;

// ---------------------------------------------------------------------------
// Full Onboarding Payload (API submission)
// ---------------------------------------------------------------------------

export const onboardingPayloadSchema = z.object({
  companyInfo: companyInfoSchema,
  invites: z.array(teamInviteSchema),
  selectedPolicies: policySelectionSchema,
  aiSettings: aiSettingsSchema,
});

export type OnboardingPayload = z.infer<typeof onboardingPayloadSchema>;
