/**
 * Onboarding API route — POST /api/v1/companies/onboarding
 *
 * Receives the full 5-step wizard data and:
 *   1. Updates company record with settings (JSONB)
 *   2. Sets onboarding_completed = true
 *   3. Creates policy records from selected templates
 *   4. Creates user records with "invited" status for team invites
 *   5. Returns success with redirect to /dashboard
 */
import { sendTeamInviteEmail } from "@/lib/services/email";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { onboardingPayloadSchema } from "@/lib/validations/onboarding";
import { NextResponse } from "next/server";

// ---------------------------------------------------------------------------
// POST handler
// ---------------------------------------------------------------------------

export async function POST(request: Request) {
  // --- Parse and validate input ---
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON in request body" }, { status: 400 });
  }

  const parsed = onboardingPayloadSchema.safeParse(body);
  if (!parsed.success) {
    const details = parsed.error.issues.map((issue) => ({
      field: issue.path.join("."),
      message: issue.message,
    }));
    return NextResponse.json({ error: "Validation failed", details }, { status: 400 });
  }

  const { companyInfo, invites, selectedPolicies, aiSettings } = parsed.data;

  // --- Get the authenticated user ---
  const supabase = await createClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // --- Get the user's company ---
  const { data: userProfile, error: profileError } = await supabase
    .from("users")
    .select("id, company_id, role")
    .eq("id", user.id)
    .single();

  if (profileError || !userProfile?.company_id) {
    console.error("[onboarding] User profile lookup failed:", profileError?.message);
    return NextResponse.json({ error: "User profile not found" }, { status: 404 });
  }

  if (userProfile.role !== "company_admin") {
    return NextResponse.json(
      { error: "Only company administrators can complete onboarding" },
      { status: 403 },
    );
  }

  const companyId = userProfile.company_id;
  const admin = createAdminClient();

  const { data: currentCompany } = await admin
    .from("companies")
    .select("settings")
    .eq("id", companyId)
    .single();

  const currentSettings = currentCompany?.settings || {};

  // --- 1. Update company record ---
  const { error: companyUpdateError } = await admin
    .from("companies")
    .update({
      name: companyInfo.name,
      industry: companyInfo.industry,
      size: companyInfo.size,
      country: companyInfo.country === "OTHER" ? "OT" : companyInfo.country.slice(0, 2),
      region: companyInfo.region,
      onboarding_completed: true,
      settings: {
        ...currentSettings,
        feature_flags: {
          ...((currentSettings.feature_flags as any) || {}),
          ai_auto_generate: aiSettings.autoGenerateDocuments ?? true,
          employee_dispute: aiSettings.allowDisputes ?? false,
        },
        ai: {
          confidenceThreshold: aiSettings.confidenceThreshold ?? 90,
          allowDisputes: aiSettings.allowDisputes ?? false,
          autoGenerateDocuments: aiSettings.autoGenerateDocuments ?? true,
        },
      },
    })
    .eq("id", companyId);

  if (companyUpdateError) {
    console.error("[onboarding] Company update failed:", companyUpdateError.message);
    return NextResponse.json(
      { error: "Failed to update company settings" },
      { status: 500 },
    );
  }

  // --- 2. Create policy records ---
  const policyRecords = selectedPolicies.map((templateId, index) => ({
    company_id: companyId,
    template_id: templateId,
    title: getPolicyTitle(templateId),
    description: getPolicyDescription(templateId),
    status: "active",
    version: 1,
    is_ai_managed: true,
    sort_order: index,
  }));

  if (policyRecords.length > 0) {
    const { error: policyError } = await admin.from("policies").insert(policyRecords);

    if (policyError) {
      console.error("[onboarding] Policy creation failed:", policyError.message);
      // Non-fatal: company is still marked as onboarded
      // Policies can be re-created later
    }
  }

  // --- 3. Create invited user records ---
  if (invites.length > 0) {
    // Generate site URL for invite links
    const siteUrl =
      process.env.NEXT_PUBLIC_SITE_URL ||
      request.headers.get("origin") ||
      "http://localhost:3000";

    for (const invite of invites) {
      // 1. Generate an invite link using Supabase Admin Auth
      const { data: linkData, error: linkError } = await admin.auth.admin.generateLink({
        type: "invite",
        email: invite.email,
        options: {
          redirectTo: `${siteUrl}/auth/accept?next=/dashboard`,
        },
      });

      if (linkError || !linkData?.properties?.action_link) {
        console.error(
          `[onboarding] Invite link generation failed for ${invite.email}:`,
          linkError?.message,
        );
        continue;
      }

      // 2. Send the customized Mailgun team invite email
      try {
        await sendTeamInviteEmail(
          invite.email,
          linkData.properties.action_link,
          companyInfo.name,
        );
      } catch (err) {
        console.error(`[onboarding] Mailgun invite failed for ${invite.email}:`, err);
        // Continue creating the profile even if email fails in case they want to retry later
      }

      // 3. Create the user profile in our users table
      const { error: inviteError } = await admin.from("users").insert({
        id: linkData.user.id,
        company_id: companyId,
        email: invite.email,
        role: invite.role === "HR_AGENT" ? "hr_agent" : "manager",
        status: "invited",
        first_name: "",
        last_name: "",
      });

      if (inviteError) {
        console.error(
          `[onboarding] Invite profile creation failed for ${invite.email}:`,
          inviteError.message,
        );
      }
    }
  }

  // --- Success ---
  const response = NextResponse.json(
    {
      success: true,
      companyId,
      redirect: "/dashboard",
    },
    { status: 200 },
  );

  response.cookies.set({
    name: "hr_onboarding_completed",
    value: "1",
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "strict",
    path: "/",
    maxAge: 60 * 60 * 8, // 8 hours
  });

  return response;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getPolicyTitle(templateId: string): string {
  const titles: Record<string, string> = {
    "attendance-punctuality": "Attendance & Punctuality Policy",
    "workplace-conduct": "Workplace Conduct Policy",
    "performance-management": "Performance Management Policy",
  };
  return titles[templateId] ?? templateId;
}

function getPolicyDescription(templateId: string): string {
  const descriptions: Record<string, string> = {
    "attendance-punctuality":
      "Covers tardiness, unexcused absences, and attendance tracking. The AI will monitor patterns and flag violations based on your configured threshold.",
    "workplace-conduct":
      "Covers insubordination, harassment, inappropriate behavior, and professional conduct standards. The AI will analyze incident reports and recommend actions.",
    "performance-management":
      "Covers poor performance, missed deadlines, and quality standards. The AI will track performance metrics and suggest progressive discipline steps.",
  };
  return descriptions[templateId] ?? "";
}
