/**
 * Settings Page — Tabbed settings for Company, Profile, Notifications, AI.
 */
"use client";

import { useEffect, useMemo, useState } from "react";
import { PageContainer } from "@/components/layout/PageContainer";
import { usePageBreadcrumbs } from "@/hooks/use-breadcrumbs";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/components/ui/toast";
import { Skeleton } from "@/components/ui/skeleton";
import { AICostTracker } from "@/components/domain/AICostTracker";
import { ReminderPanel } from "@/components/domain/ReminderPanel";
import { APIError, settingsAPI, usersAPI } from "@/lib/api/client";
import { useAuthStore } from "@/stores/auth-store";
import { Settings, Building2, User, Bell, Brain, Shield, Save } from "lucide-react";

type TabKey = "company" | "profile" | "notifications" | "ai";

type NotificationKey =
  | "newIncidentsReported"
  | "aiEvaluationComplete"
  | "documentApproved"
  | "meetingScheduled"
  | "documentAwaitingSignature"
  | "documentSigned"
  | "disputeSubmitted"
  | "aiBudgetAlerts"
  | "meetingReminder24h"
  | "signatureReminder72h";

interface CompanyFormState {
  name: string;
  industry: string;
  size: string;
  country: string;
}

interface ProfileFormState {
  firstName: string;
  lastName: string;
  phone: string;
  jobTitle: string;
  email: string;
  role: string;
}

interface SecurityFormState {
  microsoftSso: boolean;
  googleSso: boolean;
  emailPassword: boolean;
}

interface AIFormState {
  confidenceThreshold: number;
  autoGenerateDocuments: boolean;
  allowDisputes: boolean;
  aiMeetingSummaries: boolean;
  monthlyBudgetUsd: number;
}

const INDUSTRY_OPTIONS = [
  { value: "technology", label: "Technology" },
  { value: "healthcare", label: "Healthcare" },
  { value: "finance", label: "Finance" },
  { value: "education", label: "Education" },
  { value: "retail", label: "Retail" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "other", label: "Other" },
];

const COMPANY_SIZE_OPTIONS = [
  { value: "1-10", label: "1-10 employees" },
  { value: "11-50", label: "11-50 employees" },
  { value: "51-200", label: "51-200 employees" },
  { value: "201-500", label: "201-500 employees" },
  { value: "500+", label: "500+ employees" },
];

const COUNTRY_OPTIONS = [
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "UK", label: "United Kingdom" },
  { value: "AU", label: "Australia" },
];

const NOTIFICATION_CONFIG: Array<{
  key: NotificationKey;
  title: string;
  description: string;
}> = [
  {
    key: "newIncidentsReported",
    title: "New Incidents Reported",
    description: "Receive a notification when a manager reports a new incident.",
  },
  {
    key: "aiEvaluationComplete",
    title: "AI Evaluation Complete",
    description: "Notified when AI finishes evaluating an incident.",
  },
  {
    key: "documentApproved",
    title: "Document Approved",
    description: "Notified when an HR agent approves a disciplinary document.",
  },
  {
    key: "meetingScheduled",
    title: "Meeting Scheduled",
    description: "Notified when a disciplinary meeting is scheduled.",
  },
  {
    key: "documentAwaitingSignature",
    title: "Document Awaiting Signature",
    description: "Remind employees when a document requires their signature.",
  },
  {
    key: "documentSigned",
    title: "Document Signed",
    description: "Notified when an employee signs a document.",
  },
  {
    key: "disputeSubmitted",
    title: "Dispute Submitted",
    description: "Notified when an employee disputes a document.",
  },
  {
    key: "aiBudgetAlerts",
    title: "AI Budget Alerts",
    description: "Notified when AI spending reaches 50%, 80%, or 100% of monthly budget.",
  },
  {
    key: "meetingReminder24h",
    title: "Reminder: 24h Before Meeting",
    description: "Reminder notification 24 hours before a scheduled meeting.",
  },
  {
    key: "signatureReminder72h",
    title: "Reminder: 72h Before Signature Deadline",
    description: "Reminder notification 72 hours before a document signature deadline.",
  },
];

const DEFAULT_NOTIFICATIONS: Record<NotificationKey, boolean> = {
  newIncidentsReported: true,
  aiEvaluationComplete: true,
  documentApproved: true,
  meetingScheduled: true,
  documentAwaitingSignature: true,
  documentSigned: true,
  disputeSubmitted: true,
  aiBudgetAlerts: true,
  meetingReminder24h: true,
  signatureReminder72h: true,
};

const DEFAULT_COMPANY_FORM: CompanyFormState = {
  name: "",
  industry: "technology",
  size: "11-50",
  country: "US",
};

const DEFAULT_PROFILE_FORM: ProfileFormState = {
  firstName: "",
  lastName: "",
  phone: "",
  jobTitle: "",
  email: "",
  role: "",
};

const DEFAULT_SECURITY_FORM: SecurityFormState = {
  microsoftSso: false,
  googleSso: true,
  emailPassword: true,
};

const DEFAULT_AI_FORM: AIFormState = {
  confidenceThreshold: 90,
  autoGenerateDocuments: true,
  allowDisputes: true,
  aiMeetingSummaries: false,
  monthlyBudgetUsd: 50,
};

const TABS: { key: TabKey; label: string; icon: React.ReactNode }[] = [
  { key: "company", label: "Company", icon: <Building2 className="h-4 w-4" /> },
  { key: "profile", label: "Profile", icon: <User className="h-4 w-4" /> },
  { key: "notifications", label: "Notifications", icon: <Bell className="h-4 w-4" /> },
  { key: "ai", label: "AI Configuration", icon: <Brain className="h-4 w-4" /> },
];

export default function SettingsPage() {
  const setAuthUser = useAuthStore((state) => state.setUser);
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState<TabKey>("company");
  const [loading, setLoading] = useState(true);
  const [savingSection, setSavingSection] = useState<"company" | "profile" | "notifications" | "ai" | null>(null);
  const [role, setRole] = useState("");
  const [companyForm, setCompanyForm] = useState<CompanyFormState>(DEFAULT_COMPANY_FORM);
  const [profileForm, setProfileForm] = useState<ProfileFormState>(DEFAULT_PROFILE_FORM);
  const [notificationPrefs, setNotificationPrefs] =
    useState<Record<NotificationKey, boolean>>(DEFAULT_NOTIFICATIONS);
  const [securityForm, setSecurityForm] = useState<SecurityFormState>(DEFAULT_SECURITY_FORM);
  const [aiForm, setAiForm] = useState<AIFormState>(DEFAULT_AI_FORM);

  const breadcrumbs = usePageBreadcrumbs([
    { label: "Home", href: "/dashboard" },
    { label: "Settings" },
  ]);

  const isCompanyAdmin = role === "COMPANY_ADMIN" || role === "SUPER_ADMIN";

  useEffect(() => {
    let cancelled = false;

    async function loadSettings() {
      try {
        const [profileResponse, settingsResponse] = await Promise.all([
          usersAPI.me(),
          settingsAPI.get(),
        ]);

        if (cancelled) return;

        setRole(profileResponse.user.role);
        setProfileForm({
          firstName: profileResponse.user.firstName,
          lastName: profileResponse.user.lastName,
          phone: profileResponse.user.phone ?? "",
          jobTitle: profileResponse.user.jobTitle ?? "",
          email: profileResponse.user.email,
          role: profileResponse.user.role,
        });
        setCompanyForm(settingsResponse.company);
        setNotificationPrefs(settingsResponse.notifications as Record<NotificationKey, boolean>);
        setSecurityForm(settingsResponse.security);
        setAiForm(settingsResponse.ai);
      } catch (error) {
        if (cancelled) return;
        toast({
          title: "Failed to load settings",
          description:
            error instanceof APIError ? error.message : "Could not load settings right now.",
          variant: "error",
        });
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    loadSettings();

    return () => {
      cancelled = true;
    };
  }, [toast]);

  async function saveCompanySettings() {
    setSavingSection("company");
    try {
      const response = await settingsAPI.update({ company: companyForm });
      setCompanyForm(response.company);
      toast({ title: "Company settings saved", variant: "success" });
    } catch (error) {
      toast({
        title: "Failed to save company settings",
        description:
          error instanceof APIError ? error.message : "Please try again.",
        variant: "error",
      });
    } finally {
      setSavingSection(null);
    }
  }

  async function saveProfileSettings() {
    setSavingSection("profile");
    try {
      const response = await usersAPI.updateMe({
        firstName: profileForm.firstName,
        lastName: profileForm.lastName,
        phone: profileForm.phone,
        jobTitle: profileForm.jobTitle,
      });

      setProfileForm((current) => ({
        ...current,
        firstName: response.user.firstName,
        lastName: response.user.lastName,
        phone: response.user.phone ?? "",
        jobTitle: response.user.jobTitle ?? "",
      }));
      setAuthUser({
        id: response.user.id,
        email: response.user.email,
        firstName: response.user.firstName,
        lastName: response.user.lastName,
        role: response.user.role,
        avatarUrl: response.user.avatarUrl,
        tenantId: response.user.tenantId,
        tenantName: response.user.tenantName,
      });
      toast({ title: "Profile updated", variant: "success" });
    } catch (error) {
      toast({
        title: "Failed to update profile",
        description:
          error instanceof APIError ? error.message : "Please try again.",
        variant: "error",
      });
    } finally {
      setSavingSection(null);
    }
  }

  async function saveNotificationSettings() {
    setSavingSection("notifications");
    try {
      const response = await settingsAPI.update({ notifications: notificationPrefs });
      setNotificationPrefs(response.notifications as Record<NotificationKey, boolean>);
      toast({ title: "Notification preferences saved", variant: "success" });
    } catch (error) {
      toast({
        title: "Failed to save notifications",
        description:
          error instanceof APIError ? error.message : "Please try again.",
        variant: "error",
      });
    } finally {
      setSavingSection(null);
    }
  }

  async function saveAiSettings() {
    setSavingSection("ai");
    try {
      const response = await settingsAPI.update({
        security: securityForm,
        ai: aiForm,
      });
      setSecurityForm(response.security);
      setAiForm(response.ai);
      toast({ title: "AI settings saved", variant: "success" });
    } catch (error) {
      toast({
        title: "Failed to save AI settings",
        description:
          error instanceof APIError ? error.message : "Please try again.",
        variant: "error",
      });
    } finally {
      setSavingSection(null);
    }
  }

  if (loading) {
    return (
      <PageContainer
        title="Settings"
        description="Manage your account and platform configuration."
      >
        <div className="grid gap-6 lg:grid-cols-[200px_1fr]">
          <div className="space-y-2">
            {[1, 2, 3, 4].map((item) => (
              <Skeleton key={item} className="h-10 rounded-lg" />
            ))}
          </div>
          <Skeleton className="h-[520px] rounded-xl" />
        </div>
      </PageContainer>
    );
  }

  return (
    <PageContainer
      title="Settings"
      description="Manage your account and platform configuration."
    >
      <div className="grid gap-6 lg:grid-cols-[200px_1fr]">
        {/* Sidebar */}
        <nav className="flex flex-col gap-1">
          {TABS.map((tab) => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key)}
              className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium transition-colors ${
                activeTab === tab.key
                  ? "bg-brand-primary/10 text-brand-primary"
                  : "text-text-secondary hover:bg-brand-slate-light hover:text-text-primary"
              }`}
            >
              {tab.icon}
              {tab.label}
            </button>
          ))}
        </nav>

        {/* Content */}
        <div>
          {activeTab === "company" && (
            <CompanySettings
              canEdit={isCompanyAdmin}
              form={companyForm}
              security={securityForm}
              saving={savingSection === "company"}
              onChange={setCompanyForm}
              onSecurityChange={setSecurityForm}
              onSave={saveCompanySettings}
            />
          )}
          {activeTab === "profile" && (
            <ProfileSettings
              form={profileForm}
              saving={savingSection === "profile"}
              onChange={setProfileForm}
              onSave={saveProfileSettings}
            />
          )}
          {activeTab === "notifications" && (
            <NotificationSettings
              canEdit={isCompanyAdmin}
              preferences={notificationPrefs}
              saving={savingSection === "notifications"}
              onToggle={(key, checked) =>
                setNotificationPrefs((current) => ({ ...current, [key]: checked }))
              }
              onSave={saveNotificationSettings}
            />
          )}
          {activeTab === "ai" && (
            <AISettings
              canEdit={isCompanyAdmin}
              form={aiForm}
              saving={savingSection === "ai"}
              onChange={setAiForm}
              onSave={saveAiSettings}
            />
          )}
        </div>
      </div>
    </PageContainer>
  );
}

// ---------------------------------------------------------------------------
// Company Settings
// ---------------------------------------------------------------------------

function CompanySettings({
  canEdit,
  form,
  security,
  saving,
  onChange,
  onSecurityChange,
  onSave,
}: {
  canEdit: boolean;
  form: CompanyFormState;
  security: SecurityFormState;
  saving: boolean;
  onChange: React.Dispatch<React.SetStateAction<CompanyFormState>>;
  onSecurityChange: React.Dispatch<React.SetStateAction<SecurityFormState>>;
  onSave: () => void;
}) {
  return (
    <div className="grid gap-6">
      <Card className="p-6">
        <h2 className="mb-4 flex items-center gap-2 font-display text-lg font-semibold text-text-primary">
          <Building2 className="h-5 w-5" />
          Company Information
        </h2>
        <div className="grid gap-4 sm:grid-cols-2">
          <div>
            <label className="block text-sm font-medium text-text-primary">
              Company Name
            </label>
            <Input
              value={form.name}
              onChange={(event) =>
                onChange((current) => ({ ...current, name: event.target.value }))
              }
              className="mt-2"
              disabled={!canEdit}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-text-primary">
              Industry
            </label>
            <Select
              value={form.industry}
              onValueChange={(value) => onChange((current) => ({ ...current, industry: value }))}
              placeholder="Select industry..."
              options={INDUSTRY_OPTIONS}
              className="mt-2"
              disabled={!canEdit}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-text-primary">
              Company Size
            </label>
            <Select
              value={form.size}
              onValueChange={(value) => onChange((current) => ({ ...current, size: value }))}
              placeholder="Select size..."
              options={COMPANY_SIZE_OPTIONS}
              className="mt-2"
              disabled={!canEdit}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-text-primary">Country</label>
            <Select
              value={form.country}
              onValueChange={(value) => onChange((current) => ({ ...current, country: value }))}
              placeholder="Select country..."
              options={COUNTRY_OPTIONS}
              className="mt-2"
              disabled={!canEdit}
            />
          </div>
        </div>
        {!canEdit && (
          <p className="mt-4 text-xs text-text-tertiary">
            Company settings can only be changed by company administrators.
          </p>
        )}
        <div className="mt-6 flex justify-end">
          <Button onClick={onSave} disabled={!canEdit || saving}>
            <Save className="mr-1.5 h-4 w-4" />
            {saving ? "Saving..." : "Save Changes"}
          </Button>
        </div>
      </Card>

      <Card className="p-6">
        <h2 className="mb-4 flex items-center gap-2 font-display text-lg font-semibold text-text-primary">
          <Shield className="h-5 w-5" />
          Security
        </h2>
        <div className="space-y-4">
          <div className="flex items-center justify-between rounded-lg border border-border p-4">
            <div>
              <p className="text-sm font-medium text-text-primary">Microsoft SSO</p>
              <p className="text-xs text-text-tertiary">
                Allow employees to sign in with Azure AD.
              </p>
            </div>
            <Switch
              checked={security.microsoftSso}
              onCheckedChange={(checked) =>
                onSecurityChange((current) => ({ ...current, microsoftSso: checked }))
              }
              disabled={!canEdit}
            />
          </div>
          <div className="flex items-center justify-between rounded-lg border border-border p-4">
            <div>
              <p className="text-sm font-medium text-text-primary">Google SSO</p>
              <p className="text-xs text-text-tertiary">
                Allow employees to sign in with Google Workspace.
              </p>
            </div>
            <Switch
              checked={security.googleSso}
              onCheckedChange={(checked) =>
                onSecurityChange((current) => ({ ...current, googleSso: checked }))
              }
              disabled={!canEdit}
            />
          </div>
          <div className="flex items-center justify-between rounded-lg border border-border p-4">
            <div>
              <p className="text-sm font-medium text-text-primary">Email/Password</p>
              <p className="text-xs text-text-tertiary">
                Allow traditional email and password login.
              </p>
            </div>
            <Switch
              checked={security.emailPassword}
              onCheckedChange={(checked) =>
                onSecurityChange((current) => ({ ...current, emailPassword: checked }))
              }
              disabled={!canEdit}
            />
          </div>
        </div>
      </Card>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Profile Settings
// ---------------------------------------------------------------------------

function ProfileSettings({
  form,
  saving,
  onChange,
  onSave,
}: {
  form: ProfileFormState;
  saving: boolean;
  onChange: React.Dispatch<React.SetStateAction<ProfileFormState>>;
  onSave: () => void;
}) {
  return (
    <Card className="p-6">
      <h2 className="mb-4 flex items-center gap-2 font-display text-lg font-semibold text-text-primary">
        <User className="h-5 w-5" />
        Profile Settings
      </h2>
      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="block text-sm font-medium text-text-primary">
            First Name
          </label>
          <Input
            value={form.firstName}
            onChange={(event) =>
              onChange((current) => ({ ...current, firstName: event.target.value }))
            }
            className="mt-2"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-text-primary">Last Name</label>
          <Input
            value={form.lastName}
            onChange={(event) =>
              onChange((current) => ({ ...current, lastName: event.target.value }))
            }
            className="mt-2"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-text-primary">Email</label>
          <Input value={form.email} type="email" className="mt-2" disabled />
          <p className="mt-1 text-xs text-text-tertiary">
            Contact your administrator to change email.
          </p>
        </div>
        <div>
          <label className="block text-sm font-medium text-text-primary">Phone</label>
          <Input
            value={form.phone}
            onChange={(event) =>
              onChange((current) => ({ ...current, phone: event.target.value }))
            }
            className="mt-2"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-text-primary">Job Title</label>
          <Input
            value={form.jobTitle}
            onChange={(event) =>
              onChange((current) => ({ ...current, jobTitle: event.target.value }))
            }
            className="mt-2"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-text-primary">Role</label>
          <div className="mt-2">
            <Badge variant="outline">{form.role.replaceAll("_", " ")}</Badge>
          </div>
        </div>
      </div>
      <div className="mt-6 flex justify-end">
        <Button onClick={onSave} disabled={saving}>
          <Save className="mr-1.5 h-4 w-4" />
          {saving ? "Saving..." : "Save Changes"}
        </Button>
      </div>
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Notification Settings
// ---------------------------------------------------------------------------

function NotificationSettings({
  canEdit,
  preferences,
  saving,
  onToggle,
  onSave,
}: {
  canEdit: boolean;
  preferences: Record<NotificationKey, boolean>;
  saving: boolean;
  onToggle: (key: NotificationKey, checked: boolean) => void;
  onSave: () => void;
}) {
  return (
    <Card className="p-6">
      <h2 className="mb-4 flex items-center gap-2 font-display text-lg font-semibold text-text-primary">
        <Bell className="h-5 w-5" />
        Notification Preferences
      </h2>
      <div className="space-y-4">
        {NOTIFICATION_CONFIG.map((notification) => (
          <NotificationToggle
            key={notification.key}
            title={notification.title}
            description={notification.description}
            checked={preferences[notification.key]}
            disabled={!canEdit}
            onCheckedChange={(checked) => onToggle(notification.key, checked)}
          />
        ))}
      </div>
      {!canEdit && (
        <p className="mt-4 text-xs text-text-tertiary">
          Notification preferences are managed at the company level by administrators.
        </p>
      )}
      <div className="mt-6 flex justify-end">
        <Button onClick={onSave} disabled={!canEdit || saving}>
          <Save className="mr-1.5 h-4 w-4" />
          {saving ? "Saving..." : "Save Notifications"}
        </Button>
      </div>
    </Card>
  );
}

function NotificationToggle({
  title,
  description,
  checked,
  disabled,
  onCheckedChange,
}: {
  title: string;
  description: string;
  checked: boolean;
  disabled?: boolean;
  onCheckedChange: (checked: boolean) => void;
}) {
  return (
    <div className="flex items-center justify-between rounded-lg border border-border p-4">
      <div>
        <p className="text-sm font-medium text-text-primary">{title}</p>
        <p className="text-xs text-text-tertiary">{description}</p>
      </div>
      <Switch checked={checked} onCheckedChange={onCheckedChange} disabled={disabled} />
    </div>
  );
}

// ---------------------------------------------------------------------------
// AI Configuration
// ---------------------------------------------------------------------------

function AISettings({
  canEdit,
  form,
  saving,
  onChange,
  onSave,
}: {
  canEdit: boolean;
  form: AIFormState;
  saving: boolean;
  onChange: React.Dispatch<React.SetStateAction<AIFormState>>;
  onSave: () => void;
}) {
  return (
    <div className="grid gap-6">
      <AICostTracker monthlyBudget={form.monthlyBudgetUsd} />

      <Card className="p-6">
        <h2 className="mb-4 flex items-center gap-2 font-display text-lg font-semibold text-text-primary">
          <Brain className="h-5 w-5" />
          AI Behavior
        </h2>
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-text-primary">
              Default Confidence Threshold
            </label>
            <p className="text-xs text-text-tertiary">
              Minimum AI confidence required to auto-generate documents.
            </p>
            <div className="mt-2 flex items-center gap-4">
              <input
                type="range"
                min={50}
                max={99}
                value={form.confidenceThreshold}
                onChange={(event) =>
                  onChange((current) => ({
                    ...current,
                    confidenceThreshold: Number(event.target.value),
                  }))
                }
                className="flex-1 accent-brand-primary"
                disabled={!canEdit}
              />
              <span className="text-lg font-bold text-brand-primary">
                {form.confidenceThreshold}%
              </span>
            </div>
          </div>

          <div className="flex items-center justify-between rounded-lg border border-border p-4">
            <div>
              <p className="text-sm font-medium text-text-primary">
                Auto-Generate Documents
              </p>
              <p className="text-xs text-text-tertiary">
                Automatically generate disciplinary documents when confidence exceeds
                threshold.
              </p>
            </div>
            <Switch
              checked={form.autoGenerateDocuments}
              onCheckedChange={(checked) =>
                onChange((current) => ({ ...current, autoGenerateDocuments: checked }))
              }
              disabled={!canEdit}
            />
          </div>

          <div className="flex items-center justify-between rounded-lg border border-border p-4">
            <div>
              <p className="text-sm font-medium text-text-primary">
                Allow Employee Disputes
              </p>
              <p className="text-xs text-text-tertiary">
                Show dispute button on document signing screen.
              </p>
            </div>
            <Switch
              checked={form.allowDisputes}
              onCheckedChange={(checked) =>
                onChange((current) => ({ ...current, allowDisputes: checked }))
              }
              disabled={!canEdit}
            />
          </div>

          <div className="flex items-center justify-between rounded-lg border border-border p-4">
            <div>
              <p className="text-sm font-medium text-text-primary">
                AI Meeting Summaries
              </p>
              <p className="text-xs text-text-tertiary">
                Generate AI summaries after disciplinary meetings.
              </p>
            </div>
            <Switch
              checked={form.aiMeetingSummaries}
              onCheckedChange={(checked) =>
                onChange((current) => ({ ...current, aiMeetingSummaries: checked }))
              }
              disabled={!canEdit}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-text-primary">
              Monthly AI Budget
            </label>
            <p className="text-xs text-text-tertiary">
              Maximum monthly spend on AI services. Calls are blocked when exceeded.
            </p>
            <div className="mt-2 flex items-center gap-2">
              <span className="text-sm text-text-tertiary">$</span>
              <Input
                value={String(form.monthlyBudgetUsd)}
                onChange={(event) =>
                  onChange((current) => ({
                    ...current,
                    monthlyBudgetUsd: Number(event.target.value || 0),
                  }))
                }
                type="number"
                step="0.01"
                className="w-32"
                disabled={!canEdit}
              />
              <span className="text-xs text-text-tertiary">per month</span>
            </div>
          </div>
        </div>

        {!canEdit && (
          <p className="mt-4 text-xs text-text-tertiary">
            AI configuration is limited to company administrators.
          </p>
        )}

        <div className="mt-6 flex justify-end">
          <Button onClick={onSave} disabled={!canEdit || saving}>
            <Save className="mr-1.5 h-4 w-4" />
            {saving ? "Saving..." : "Save AI Settings"}
          </Button>
        </div>
      </Card>

      <ReminderPanel />
    </div>
  );
}
