/**
 * Policy Builder — 4-Step Wizard for Company Admins.
 *
 * Step 1: Basic Info (title, category, effective date, rich text content)
 * Step 2: Structured Rules (add/edit/delete rules, escalation ladder)
 * Step 3: AI Settings (threshold override, toggles, test panel)
 * Step 4: Review + Activate
 *
 * Connects to Policy API (T017) for create/update.
 */
"use client";

import { useState, useCallback, useMemo } from "react";
import { PageContainer } from "@/components/layout/PageContainer";
import { usePageBreadcrumbs } from "@/hooks/use-breadcrumbs";
import { FormStepIndicator } from "@/components/domain/FormStepIndicator";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { EmptyState } from "@/components/ui/empty-state";
import {
  FileText,
  ListChecks,
  Brain,
  CheckCircle,
  Plus,
  Trash2,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  AlertTriangle,
  TestTube,
} from "lucide-react";
import Link from "next/link";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface PolicyRule {
  id: string;
  name: string;
  triggerType: string;
  severity: string;
  actionType: string;
  escalationLevel: number;
  description: string;
}

interface PolicyFormData {
  title: string;
  category: string;
  effectiveDate: string;
  content: string;
  rules: PolicyRule[];
  aiThreshold: number;
  autoGenerateDocuments: boolean;
  allowDisputes: boolean;
}

const CATEGORIES = [
  "Attendance & Punctuality",
  "Workplace Conduct",
  "Performance Management",
  "Safety & Health",
  "Technology & Data Security",
  "Leave & Time Off",
  "Compensation & Benefits",
  "Other",
];

const TRIGGER_TYPES = [
  { value: "tardiness", label: "Tardiness" },
  { value: "absence", label: "Absence" },
  { value: "insubordination", label: "Insubordination" },
  { value: "performance", label: "Performance" },
  { value: "misconduct", label: "Misconduct" },
  { value: "violation_of_policy", label: "Policy Violation" },
];

const ACTION_TYPES = [
  { value: "verbal_warning", label: "Verbal Warning" },
  { value: "written_warning", label: "Written Warning" },
  { value: "pip", label: "Performance Improvement Plan" },
  { value: "termination_review", label: "Termination Review" },
];

const SEVERITY_LEVELS = [
  { value: "low", label: "Low" },
  { value: "medium", label: "Medium" },
  { value: "high", label: "High" },
  { value: "critical", label: "Critical" },
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function PolicyBuilderPage() {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState<PolicyFormData>({
    title: "",
    category: "",
    effectiveDate: new Date().toISOString().split("T")[0],
    content: "",
    rules: [],
    aiThreshold: 90,
    autoGenerateDocuments: true,
    allowDisputes: true,
  });

  const breadcrumbs = usePageBreadcrumbs([
    { label: "Home", href: "/dashboard" },
    { label: "Policies", href: "/policies" },
    { label: "Create Policy" },
  ]);

  const updateField = useCallback(
    <K extends keyof PolicyFormData>(field: K, value: PolicyFormData[K]) => {
      setFormData((prev) => ({ ...prev, [field]: value }));
    },
    [],
  );

  const canProceed = useMemo(() => {
    switch (step) {
      case 1:
        return (
          formData.title.trim().length >= 3 &&
          formData.category &&
          formData.content.trim().length >= 10
        );
      case 2:
        return formData.rules.length >= 1;
      case 3:
        return true;
      case 4:
        return true;
      default:
        return false;
    }
  }, [step, formData]);

  const handleSubmit = useCallback(() => {
    // TODO: POST /api/v1/policies
    console.log("Creating policy:", formData);
  }, [formData]);

  return (
    <PageContainer
      title="Create Policy"
      description="Define a new disciplinary policy with rules and AI settings."
    >
      <div className="mx-auto max-w-4xl">
        <FormStepIndicator
          currentStep={step}
          steps={[
            { number: 1, label: "Basic Info" },
            { number: 2, label: "Rules" },
            { number: 3, label: "AI Settings" },
            { number: 4, label: "Review" },
          ]}
          completedSteps={Array.from({ length: step - 1 }, (_, i) => i + 1)}
        />

        <Card className="mt-6 p-6">
          {step === 1 && (
            <Step1BasicInfo
              title={formData.title}
              category={formData.category}
              effectiveDate={formData.effectiveDate}
              content={formData.content}
              onTitleChange={(v) => updateField("title", v)}
              onCategoryChange={(v) => updateField("category", v)}
              onDateChange={(v) => updateField("effectiveDate", v)}
              onContentChange={(v) => updateField("content", v)}
            />
          )}
          {step === 2 && (
            <Step2Rules
              rules={formData.rules}
              onAddRule={(rule) => updateField("rules", [...formData.rules, rule])}
              onUpdateRule={(index, rule) => {
                const updated = [...formData.rules];
                updated[index] = rule;
                updateField("rules", updated);
              }}
              onDeleteRule={(index) => {
                updateField(
                  "rules",
                  formData.rules.filter((_, i) => i !== index),
                );
              }}
              onMoveRule={(index, direction) => {
                const updated = [...formData.rules];
                const target = direction === "up" ? index - 1 : index + 1;
                if (target < 0 || target >= updated.length) return;
                [updated[index], updated[target]] = [updated[target], updated[index]];
                updateField("rules", updated);
              }}
            />
          )}
          {step === 3 && (
            <Step3AISettings
              threshold={formData.aiThreshold}
              autoGenerate={formData.autoGenerateDocuments}
              allowDisputes={formData.allowDisputes}
              onThresholdChange={(v) => updateField("aiThreshold", v)}
              onAutoGenerateChange={(v) => updateField("autoGenerateDocuments", v)}
              onAllowDisputesChange={(v) => updateField("allowDisputes", v)}
            />
          )}
          {step === 4 && <Step4Review formData={formData} />}

          {/* Navigation */}
          <div className="mt-6 flex items-center justify-between border-t border-border pt-4">
            <Button
              variant="ghost"
              onClick={() => setStep((s) => Math.max(1, s - 1))}
              disabled={step === 1}
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back
            </Button>

            {step < 4 ? (
              <Button
                onClick={() => setStep((s) => Math.min(4, s + 1))}
                disabled={!canProceed}
              >
                Continue
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            ) : (
              <div className="flex gap-2">
                <Button variant="outline" asChild>
                  <Link href="/policies">Save as Draft</Link>
                </Button>
                <Button onClick={handleSubmit} disabled={!canProceed}>
                  <CheckCircle className="mr-2 h-4 w-4" />
                  Activate Policy
                </Button>
              </div>
            )}
          </div>
        </Card>
      </div>
    </PageContainer>
  );
}

// ---------------------------------------------------------------------------
// Step 1: Basic Info
// ---------------------------------------------------------------------------

function Step1BasicInfo({
  title,
  category,
  effectiveDate,
  content,
  onTitleChange,
  onCategoryChange,
  onDateChange,
  onContentChange,
}: {
  title: string;
  category: string;
  effectiveDate: string;
  content: string;
  onTitleChange: (v: string) => void;
  onCategoryChange: (v: string) => void;
  onDateChange: (v: string) => void;
  onContentChange: (v: string) => void;
}) {
  return (
    <div className="space-y-6">
      <div>
        <label className="block text-sm font-medium text-text-primary">
          Policy Title <span className="text-brand-error">*</span>
        </label>
        <Input
          value={title}
          onChange={(e) => onTitleChange(e.target.value)}
          placeholder="e.g., Attendance & Punctuality Policy"
          className="mt-2"
          maxLength={255}
        />
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="block text-sm font-medium text-text-primary">
            Category <span className="text-brand-error">*</span>
          </label>
          <Select
            value={category}
            onValueChange={onCategoryChange}
            placeholder="Select category..."
            options={CATEGORIES.map((c) => ({ value: c, label: c }))}
            className="mt-2"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-text-primary">
            Effective Date
          </label>
          <Input
            type="date"
            value={effectiveDate}
            onChange={(e) => onDateChange(e.target.value)}
            className="mt-2"
          />
        </div>
      </div>

      <div>
        <label className="block text-sm font-medium text-text-primary">
          Policy Content <span className="text-brand-error">*</span>
        </label>
        <p className="text-xs text-text-tertiary">
          The full policy text. This is used as context for AI evaluation.
        </p>
        <Textarea
          value={content}
          onChange={(e) => onContentChange(e.target.value)}
          placeholder="Enter the full policy text..."
          className="mt-2 min-h-[200px]"
          maxLength={10000}
        />
        <p className="mt-1 text-right text-xs text-text-tertiary">
          {content.length}/10,000
        </p>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Step 2: Structured Rules
// ---------------------------------------------------------------------------

function Step2Rules({
  rules,
  onAddRule,
  onUpdateRule,
  onDeleteRule,
  onMoveRule,
}: {
  rules: PolicyRule[];
  onAddRule: (rule: PolicyRule) => void;
  onUpdateRule: (index: number, rule: PolicyRule) => void;
  onDeleteRule: (index: number) => void;
  onMoveRule: (index: number, direction: "up" | "down") => void;
}) {
  const addEmptyRule = () => {
    onAddRule({
      id: crypto.randomUUID(),
      name: "",
      triggerType: "",
      severity: "low",
      actionType: "verbal_warning",
      escalationLevel: 1,
      description: "",
    });
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-base font-semibold text-text-primary">Policy Rules</h3>
          <p className="text-sm text-text-tertiary">
            Define trigger → condition → action rules for AI evaluation.
          </p>
        </div>
        <Button size="sm" onClick={addEmptyRule}>
          <Plus className="mr-1.5 h-4 w-4" />
          Add Rule
        </Button>
      </div>

      {rules.length === 0 ? (
        <EmptyState
          title="No rules defined"
          description="Add at least one rule to define how AI should evaluate incidents."
          icon={<ListChecks className="h-8 w-8" />}
        />
      ) : (
        <div className="space-y-3">
          {rules.map((rule, index) => (
            <RuleEditor
              key={rule.id}
              rule={rule}
              index={index}
              totalRules={rules.length}
              onChange={(updated) => onUpdateRule(index, updated)}
              onDelete={() => onDeleteRule(index)}
              onMove={(dir) => onMoveRule(index, dir)}
            />
          ))}
        </div>
      )}

      {/* Escalation Ladder Visualization */}
      {rules.length > 0 && (
        <Card className="p-4">
          <h4 className="mb-3 text-sm font-semibold text-text-primary">
            Escalation Ladder
          </h4>
          <div className="flex items-center gap-2 overflow-x-auto">
            {ACTION_TYPES.map((action, i) => {
              const hasRuleForLevel = rules.some((r) => r.escalationLevel === i + 1);
              return (
                <div key={action.value} className="flex flex-col items-center">
                  <div
                    className={`flex h-12 w-24 items-center justify-center rounded-lg border text-xs font-medium ${
                      hasRuleForLevel
                        ? "border-brand-primary bg-brand-primary/10 text-brand-primary"
                        : "border-border text-text-tertiary"
                    }`}
                  >
                    {action.label}
                  </div>
                  <span className="mt-1 text-[10px] text-text-tertiary">
                    Level {i + 1}
                  </span>
                  {i < ACTION_TYPES.length - 1 && (
                    <div className="absolute -mt-6 ml-24 h-px w-4 bg-border" />
                  )}
                </div>
              );
            })}
          </div>
        </Card>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Rule Editor
// ---------------------------------------------------------------------------

function RuleEditor({
  rule,
  index,
  totalRules,
  onChange,
  onDelete,
  onMove,
}: {
  rule: PolicyRule;
  index: number;
  totalRules: number;
  onChange: (rule: PolicyRule) => void;
  onDelete: () => void;
  onMove: (dir: "up" | "down") => void;
}) {
  return (
    <Card className="p-4">
      <div className="flex items-start justify-between">
        <h4 className="text-sm font-medium text-text-primary">Rule #{index + 1}</h4>
        <div className="flex gap-1">
          <button
            onClick={() => onMove("up")}
            disabled={index === 0}
            className="rounded p-1 text-text-tertiary hover:text-text-primary disabled:opacity-30"
          >
            <ArrowUp className="h-4 w-4" />
          </button>
          <button
            onClick={() => onMove("down")}
            disabled={index === totalRules - 1}
            className="rounded p-1 text-text-tertiary hover:text-text-primary disabled:opacity-30"
          >
            <ArrowDown className="h-4 w-4" />
          </button>
          <button
            onClick={onDelete}
            className="rounded p-1 text-brand-error hover:text-brand-error-dim"
          >
            <Trash2 className="h-4 w-4" />
          </button>
        </div>
      </div>

      <div className="mt-3 grid gap-3 sm:grid-cols-2">
        <div>
          <label className="text-xs font-medium text-text-tertiary">Rule Name</label>
          <Input
            value={rule.name}
            onChange={(e) => onChange({ ...rule, name: e.target.value })}
            placeholder="e.g., Repeated Tardiness"
            className="mt-1"
          />
        </div>
        <div>
          <label className="text-xs font-medium text-text-tertiary">Trigger Type</label>
          <Select
            value={rule.triggerType}
            onValueChange={(v) => onChange({ ...rule, triggerType: v })}
            placeholder="Select trigger..."
            options={TRIGGER_TYPES}
            className="mt-1"
          />
        </div>
        <div>
          <label className="text-xs font-medium text-text-tertiary">Severity</label>
          <Select
            value={rule.severity}
            onValueChange={(v) => onChange({ ...rule, severity: v })}
            placeholder="Select severity..."
            options={SEVERITY_LEVELS}
            className="mt-1"
          />
        </div>
        <div>
          <label className="text-xs font-medium text-text-tertiary">Action Type</label>
          <Select
            value={rule.actionType}
            onValueChange={(v) => onChange({ ...rule, actionType: v })}
            placeholder="Select action..."
            options={ACTION_TYPES}
            className="mt-1"
          />
        </div>
        <div>
          <label className="text-xs font-medium text-text-tertiary">
            Escalation Level
          </label>
          <Input
            type="number"
            min={1}
            max={10}
            value={rule.escalationLevel}
            onChange={(e) =>
              onChange({ ...rule, escalationLevel: parseInt(e.target.value) || 1 })
            }
            className="mt-1"
          />
        </div>
        <div className="sm:col-span-2">
          <label className="text-xs font-medium text-text-tertiary">Description</label>
          <Textarea
            value={rule.description}
            onChange={(e) => onChange({ ...rule, description: e.target.value })}
            placeholder="Describe when this rule applies..."
            className="mt-1 min-h-[60px]"
          />
        </div>
      </div>
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Step 3: AI Settings
// ---------------------------------------------------------------------------

function Step3AISettings({
  threshold,
  autoGenerate,
  allowDisputes,
  onThresholdChange,
  onAutoGenerateChange,
  onAllowDisputesChange,
}: {
  threshold: number;
  autoGenerate: boolean;
  allowDisputes: boolean;
  onThresholdChange: (v: number) => void;
  onAutoGenerateChange: (v: boolean) => void;
  onAllowDisputesChange: (v: boolean) => void;
}) {
  return (
    <div className="space-y-6">
      <div className="rounded-lg border border-border p-4">
        <h3 className="text-sm font-semibold text-text-primary">
          AI Confidence Threshold
        </h3>
        <p className="mt-1 text-xs text-text-tertiary">
          Minimum confidence score required for AI to auto-generate documents. Below this
          threshold, incidents route to manual HR review.
        </p>
        <div className="mt-4">
          <div className="flex items-center justify-between">
            <span className="text-xs text-text-tertiary">50%</span>
            <span className="text-2xl font-bold text-brand-primary">{threshold}%</span>
            <span className="text-xs text-text-tertiary">99%</span>
          </div>
          <input
            type="range"
            min={50}
            max={99}
            value={threshold}
            onChange={(e) => onThresholdChange(parseInt(e.target.value))}
            className="mt-2 w-full accent-brand-primary"
          />
          <div className="mt-1 flex justify-between text-[10px] text-text-tertiary">
            <span>More lenient</span>
            <span>More strict</span>
          </div>
        </div>
      </div>

      <div className="space-y-4">
        <div className="flex items-center justify-between rounded-lg border border-border p-4">
          <div>
            <p className="text-sm font-medium text-text-primary">
              Auto-Generate Documents
            </p>
            <p className="text-xs text-text-tertiary">
              When AI confidence exceeds threshold, automatically generate disciplinary
              documents.
            </p>
          </div>
          <Switch checked={autoGenerate} onCheckedChange={onAutoGenerateChange} />
        </div>

        <div className="flex items-center justify-between rounded-lg border border-border p-4">
          <div>
            <p className="text-sm font-medium text-text-primary">
              Allow Employee Disputes
            </p>
            <p className="text-xs text-text-tertiary">
              Show a "Dispute" button on the document signing screen for employees.
            </p>
          </div>
          <Switch checked={allowDisputes} onCheckedChange={onAllowDisputesChange} />
        </div>
      </div>

      {/* AI Test Panel */}
      <Card className="p-4">
        <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-text-primary">
          <TestTube className="h-4 w-4" />
          AI Test Panel
        </h3>
        <p className="text-xs text-text-tertiary">
          Test how AI will interpret these rules with a sample scenario.
        </p>
        <div className="mt-3 rounded-lg border border-dashed border-border p-4 text-center">
          <TestTube className="mx-auto mb-2 h-8 w-8 text-text-tertiary" />
          <p className="text-sm text-text-tertiary">Available after policy is saved.</p>
        </div>
      </Card>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Step 4: Review
// ---------------------------------------------------------------------------

function Step4Review({ formData }: { formData: PolicyFormData }) {
  return (
    <div className="space-y-6">
      <Card className="p-4">
        <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-text-primary">
          <FileText className="h-4 w-4" />
          Basic Information
        </h3>
        <div className="space-y-1 text-sm text-text-secondary">
          <p>
            <span className="text-text-tertiary">Title:</span> {formData.title}
          </p>
          <p>
            <span className="text-text-tertiary">Category:</span> {formData.category}
          </p>
          <p>
            <span className="text-text-tertiary">Effective Date:</span>{" "}
            {formData.effectiveDate}
          </p>
        </div>
      </Card>

      <Card className="p-4">
        <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-text-primary">
          <ListChecks className="h-4 w-4" />
          Rules ({formData.rules.length})
        </h3>
        <div className="space-y-2">
          {formData.rules.map((rule, i) => (
            <div
              key={rule.id}
              className="flex items-center gap-2 rounded-lg border border-border p-2"
            >
              <Badge variant="warning">Level {rule.escalationLevel}</Badge>
              <span className="text-sm text-text-primary">
                {rule.name || `Rule #${i + 1}`}
              </span>
              <span className="text-xs text-text-tertiary">→</span>
              <span className="text-sm text-text-secondary">
                {rule.actionType.replace(/_/g, " ")}
              </span>
            </div>
          ))}
          {formData.rules.length === 0 && (
            <p className="text-sm text-text-tertiary">No rules defined.</p>
          )}
        </div>
      </Card>

      <Card className="p-4">
        <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-text-primary">
          <Brain className="h-4 w-4" />
          AI Settings
        </h3>
        <div className="space-y-2 text-sm text-text-secondary">
          <p>
            <span className="text-text-tertiary">Confidence Threshold:</span>{" "}
            {formData.aiThreshold}%
          </p>
          <p>
            <span className="text-text-tertiary">Auto-Generate:</span>{" "}
            {formData.autoGenerateDocuments ? "Enabled" : "Disabled"}
          </p>
          <p>
            <span className="text-text-tertiary">Employee Disputes:</span>{" "}
            {formData.allowDisputes ? "Enabled" : "Disabled"}
          </p>
        </div>
      </Card>

      <div className="rounded-lg border border-brand-primary/30 bg-brand-primary/5 p-4">
        <h4 className="text-sm font-semibold text-brand-primary">
          How AI Will Interpret This Policy
        </h4>
        <p className="mt-2 text-sm text-text-secondary">
          When a manager reports an incident matching one of your rules (trigger type +
          severity), the AI will evaluate it against this policy. If the confidence score
          is at least {formData.aiThreshold}%, a{" "}
          {formData.autoGenerateDocuments
            ? "disciplinary document will be auto-generated"
            : "notification will be sent for manual review"}
          .
          {formData.allowDisputes &&
            " Employees will be able to dispute signed documents."}
        </p>
      </div>
    </div>
  );
}
