// ============================================
// HMN — Onboarding Store (Zustand)
// Persists wizard progress to localStorage
// so users can resume from their last step.
// ============================================

import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { CompanyInfo, TeamInvite, AISettings } from "@/lib/validations/onboarding";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface OnboardingState {
  /** Current active step (1-based) */
  currentStep: number;
  /** Steps that have been completed (the user can navigate back to review) */
  completedSteps: number[];
  /** Step 1 data */
  companyInfo: CompanyInfo;
  /** Step 2 data — may be empty array (optional step) */
  invites: TeamInvite[];
  /** Step 3 data — IDs of selected AI policy templates */
  selectedPolicies: string[];
  /** Step 4 data */
  aiSettings: AISettings;
}

// ---------------------------------------------------------------------------
// Default state
// ---------------------------------------------------------------------------

const defaultCompanyInfo: CompanyInfo = {
  name: "",
  industry: "Technology",
  size: "1-10",
  country: "",
  region: "",
};

const defaultAISettings: AISettings = {
  confidenceThreshold: 90,
  allowDisputes: false,
  autoGenerateDocuments: true,
};

const initialState: OnboardingState = {
  currentStep: 1,
  completedSteps: [],
  companyInfo: defaultCompanyInfo,
  invites: [],
  selectedPolicies: [],
  aiSettings: defaultAISettings,
};

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

export interface OnboardingActions {
  /** Move to the next step (marks current as completed) */
  nextStep: () => void;
  /** Go back to a previous step */
  prevStep: () => void;
  /** Jump to a specific completed step for review */
  goToStep: (step: number) => void;
  /** Update company info (Step 1) */
  setCompanyInfo: (info: Partial<CompanyInfo>) => void;
  /** Replace the entire invite list (Step 2) */
  setInvites: (invites: TeamInvite[]) => void;
  /** Add a single invite */
  addInvite: (invite: TeamInvite) => void;
  /** Remove an invite by index */
  removeInvite: (index: number) => void;
  /** Update a single invite by index */
  updateInvite: (index: number, update: Partial<TeamInvite>) => void;
  /** Toggle a policy selection (Step 3) */
  togglePolicy: (policyId: string) => void;
  /** Set selected policies directly */
  setSelectedPolicies: (policyIds: string[]) => void;
  /** Update AI settings (Step 4) */
  setAISettings: (settings: Partial<AISettings>) => void;
  /** Reset the entire wizard */
  reset: () => void;
  /** Mark wizard as completed and clear persisted data */
  completeAndClear: () => void;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useOnboardingStore = create<OnboardingState & OnboardingActions>()(
  persist(
    (set, get) => ({
      ...initialState,

      nextStep: () =>
        set((state) => {
          const completed = [
            ...new Set([...state.completedSteps, state.currentStep]),
          ].sort((a, b) => a - b);
          const next = Math.min(state.currentStep + 1, 5);
          return { currentStep: next, completedSteps: completed };
        }),

      prevStep: () =>
        set((state) => ({
          currentStep: Math.max(state.currentStep - 1, 1),
        })),

      goToStep: (step) => {
        const { completedSteps } = get();
        // Only allow jumping to completed steps or the current step
        if (completedSteps.includes(step) || step <= Math.max(...completedSteps, 0) + 1) {
          set({ currentStep: step });
        }
      },

      setCompanyInfo: (info) =>
        set((state) => ({
          companyInfo: { ...state.companyInfo, ...info },
        })),

      setInvites: (invites) => set({ invites }),

      addInvite: (invite) => set((state) => ({ invites: [...state.invites, invite] })),

      removeInvite: (index) =>
        set((state) => ({
          invites: state.invites.filter((_, i) => i !== index),
        })),

      updateInvite: (index, update) =>
        set((state) => ({
          invites: state.invites.map((inv, i) =>
            i === index ? { ...inv, ...update } : inv,
          ),
        })),

      togglePolicy: (policyId) =>
        set((state) => ({
          selectedPolicies: state.selectedPolicies.includes(policyId)
            ? state.selectedPolicies.filter((id) => id !== policyId)
            : [...state.selectedPolicies, policyId],
        })),

      setSelectedPolicies: (policyIds) => set({ selectedPolicies: policyIds }),

      setAISettings: (settings) =>
        set((state) => ({
          aiSettings: { ...state.aiSettings, ...settings },
        })),

      reset: () => set(initialState),

      completeAndClear: () => set(initialState),
    }),
    {
      name: "hmn-onboarding",
      // Persist the full wizard state so users can resume
      partialize: (state) => ({
        currentStep: state.currentStep,
        completedSteps: state.completedSteps,
        companyInfo: state.companyInfo,
        invites: state.invites,
        selectedPolicies: state.selectedPolicies,
        aiSettings: state.aiSettings,
      }),
    },
  ),
);
