// ============================================
// HMN — Step 5: Review & Activate
// Summary of all settings + plain English AI summary
// ============================================

"use client";

import { useCallback, useState } from "react";
import { useRouter } from "next/navigation";
import {
  CheckCircle2,
  Loader2,
  Building2,
  Users,
  Shield,
  Brain,
  Rocket,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useOnboardingStore } from "@/stores/onboarding-store";
import {
  POLICY_TEMPLATES,
  COUNTRY_OPTIONS,
  type OnboardingPayload,
} from "@/lib/validations/onboarding";

// ---------------------------------------------------------------------------
// Helper — country name from code
// ---------------------------------------------------------------------------

function getCountryName(code: string): string {
  const country = COUNTRY_OPTIONS.find((c) => c.value === code);
  return country?.label ?? code;
}

// ---------------------------------------------------------------------------
// Helper — role display name
// ---------------------------------------------------------------------------

function getRoleLabel(role: string): string {
  switch (role) {
    case "HR_AGENT":
      return "HR Agent";
    case "MANAGER":
      return "Manager";
    default:
      return role;
  }
}

// ---------------------------------------------------------------------------
// Helper — generate plain-English AI summary
// ---------------------------------------------------------------------------

function generateAISummary(
  selectedPolicies: string[],
  aiSettings: {
    confidenceThreshold: number;
    allowDisputes: boolean;
    autoGenerateDocuments: boolean;
  },
): string {
  const policyNames = selectedPolicies
    .map((id) => POLICY_TEMPLATES.find((t) => t.id === id)?.title)
    .filter(Boolean);

  const thresholdZone =
    aiSettings.confidenceThreshold >= 80
      ? "only when it is highly confident"
      : aiSettings.confidenceThreshold >= 60
        ? "when it has moderate confidence"
        : "even with limited confidence";

  const disputeText = aiSettings.allowDisputes
    ? "Employees will be able to dispute any AI-recommended disciplinary action, which triggers a human review process."
    : "AI decisions will be final unless a manager manually intervenes.";

  const autoGenText = aiSettings.autoGenerateDocuments
    ? `When the AI's confidence exceeds ${aiSettings.confidenceThreshold}%, it will automatically draft relevant documents (e.g., warning letters, incident reports).`
    : "Documents will only be generated when manually requested by an HR agent or manager.";

  return `Your AI assistant will monitor compliance with your ${policyNames.length === 1 ? "policy" : "policies"} (${policyNames.join(", ")}). It will recommend actions ${thresholdZone} — specifically when confidence is at or above ${aiSettings.confidenceThreshold}%. ${disputeText} ${autoGenText}`;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function StepReviewActivate() {
  const router = useRouter();
  const { companyInfo, invites, selectedPolicies, aiSettings, completeAndClear } =
    useOnboardingStore();

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Build the payload
  const payload: OnboardingPayload = {
    companyInfo,
    invites,
    selectedPolicies,
    aiSettings,
  };

  const aiSummary = generateAISummary(selectedPolicies, aiSettings);

  // ---------------------------------------------------------------------------
  // Submit handler
  // ---------------------------------------------------------------------------

  const handleActivate = useCallback(async () => {
    setIsSubmitting(true);
    setError(null);

    try {
      const response = await fetch("/api/v1/companies/onboarding", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        const data = await response.json();
        setError(data.error ?? "Failed to save onboarding data. Please try again.");
        return;
      }

      // Clear persisted state and redirect
      completeAndClear();
      router.push("/dashboard");
      router.refresh();
    } catch {
      setError("Network error. Please check your connection and try again.");
    } finally {
      setIsSubmitting(false);
    }
  }, [payload, completeAndClear, router]);

  const handleSaveDraft = useCallback(() => {
    // State is already persisted to localStorage via Zustand persist middleware.
    // Just redirect back to dashboard — the user can resume later.
    router.push("/dashboard");
  }, [router]);

  // ---------------------------------------------------------------------------
  // Selected policy details
  // ---------------------------------------------------------------------------

  const selectedPolicyDetails = selectedPolicies
    .map((id) => POLICY_TEMPLATES.find((t) => t.id === id))
    .filter(Boolean);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-brand-primary/10">
          <Rocket className="h-6 w-6 text-brand-primary" />
        </div>
        <div>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            Review & Activate
          </h2>
          <p className="text-sm text-text-secondary">
            Review your settings before activating your AI-powered HR workspace
          </p>
        </div>
      </div>

      {/* Company Info Summary */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Building2 className="h-4 w-4 text-brand-primary" />
            <CardTitle className="text-sm">Company Information</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
            <div>
              <dt className="text-text-tertiary">Name</dt>
              <dd className="font-medium text-text-primary">{companyInfo.name}</dd>
            </div>
            <div>
              <dt className="text-text-tertiary">Industry</dt>
              <dd className="font-medium text-text-primary">{companyInfo.industry}</dd>
            </div>
            <div>
              <dt className="text-text-tertiary">Size</dt>
              <dd className="font-medium text-text-primary">
                {companyInfo.size} employees
              </dd>
            </div>
            <div>
              <dt className="text-text-tertiary">Location</dt>
              <dd className="font-medium text-text-primary">
                {companyInfo.region}, {getCountryName(companyInfo.country)}
              </dd>
            </div>
          </dl>
        </CardContent>
      </Card>

      {/* Team Invites Summary */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Users className="h-4 w-4 text-brand-primary" />
            <CardTitle className="text-sm">Team Invites</CardTitle>
            {invites.length > 0 && <Badge variant="default">{invites.length}</Badge>}
          </div>
        </CardHeader>
        <CardContent>
          {invites.length === 0 ? (
            <p className="text-sm text-text-tertiary">No team members invited yet.</p>
          ) : (
            <ul className="space-y-1">
              {invites.map((invite, index) => (
                <li key={index} className="flex items-center justify-between text-sm">
                  <span className="text-text-primary">{invite.email}</span>
                  <Badge variant="outline">{getRoleLabel(invite.role)}</Badge>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>

      {/* Policies Summary */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Shield className="h-4 w-4 text-brand-primary" />
            <CardTitle className="text-sm">Active Policies</CardTitle>
            <Badge variant="success">{selectedPolicies.length}</Badge>
          </div>
        </CardHeader>
        <CardContent>
          <ul className="space-y-1">
            {selectedPolicyDetails.map((policy) => (
              <li key={policy!.id} className="flex items-center gap-2 text-sm">
                <CheckCircle2 className="h-4 w-4 text-brand-success" />
                <span className="text-text-primary">{policy!.title}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* AI Settings Summary */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Brain className="h-4 w-4 text-brand-primary" />
            <CardTitle className="text-sm">AI Configuration</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
            <div>
              <dt className="text-text-tertiary">Confidence Threshold</dt>
              <dd className="font-medium text-text-primary">
                {aiSettings.confidenceThreshold}%
              </dd>
            </div>
            <div>
              <dt className="text-text-tertiary">Allow Disputes</dt>
              <dd className="font-medium text-text-primary">
                {aiSettings.allowDisputes ? "Yes" : "No"}
              </dd>
            </div>
            <div>
              <dt className="text-text-tertiary">Auto-Generate Documents</dt>
              <dd className="font-medium text-text-primary">
                {aiSettings.autoGenerateDocuments ? "Yes" : "No"}
              </dd>
            </div>
          </dl>
        </CardContent>
      </Card>

      {/* AI Summary in Plain English */}
      <div className="rounded-xl border border-brand-primary/20 bg-brand-primary/5 p-5">
        <div className="mb-2 flex items-center gap-2">
          <Brain className="h-4 w-4 text-brand-primary" />
          <h3 className="text-sm font-semibold text-brand-primary">
            How AI Will Interpret Your Policies
          </h3>
        </div>
        <p className="text-sm leading-relaxed text-text-secondary">{aiSummary}</p>
      </div>

      {/* Error */}
      {error && (
        <div
          className="rounded-lg border border-brand-error/30 bg-brand-error/10 px-4 py-3 text-sm text-brand-error"
          role="alert"
        >
          {error}
        </div>
      )}

      {/* Actions */}
      <div className="flex flex-col gap-3 pt-2 sm:flex-row sm:justify-between">
        <Button
          type="button"
          variant="ghost"
          onClick={handleSaveDraft}
          disabled={isSubmitting}
        >
          Save as Draft
        </Button>
        <Button
          type="button"
          size="lg"
          onClick={handleActivate}
          disabled={isSubmitting}
          className="min-w-[200px] font-bold"
        >
          {isSubmitting ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Activating...
            </>
          ) : (
            "Activate Workspace"
          )}
        </Button>
      </div>
    </div>
  );
}
