// ============================================
// HMN — Step 4: AI Settings
// Confidence threshold slider + toggles
// ============================================

"use client";

import { useCallback, useState } from "react";
import { Brain, Info } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { FormField } from "@/components/ui/form-field";
import { useOnboardingStore } from "@/stores/onboarding-store";
import { aiSettingsSchema, type AISettings } from "@/lib/validations/onboarding";
import { cn } from "@/lib/utils";

// ---------------------------------------------------------------------------
// Confidence zone helper
// ---------------------------------------------------------------------------

function getThresholdZone(value: number): "green" | "yellow" | "red" {
  if (value >= 80) return "green";
  if (value >= 60) return "yellow";
  return "red";
}

function getZoneColor(zone: "green" | "yellow" | "red") {
  switch (zone) {
    case "green":
      return "text-brand-success";
    case "yellow":
      return "text-brand-warning";
    case "red":
      return "text-brand-error";
  }
}

function getZoneBg(zone: "green" | "yellow" | "red") {
  switch (zone) {
    case "green":
      return "bg-brand-success";
    case "yellow":
      return "bg-brand-warning";
    case "red":
      return "bg-brand-error";
  }
}

function getZoneLabel(zone: "green" | "yellow" | "red") {
  switch (zone) {
    case "green":
      return "High confidence — AI will only act when very certain";
    case "yellow":
      return "Moderate confidence — AI may occasionally need human review";
    case "red":
      return "Low threshold — AI will act more aggressively with less certainty";
  }
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

interface StepAISettingsProps {
  onNext: () => void;
  onPrev: () => void;
}

export function StepAISettings({ onNext, onPrev }: StepAISettingsProps) {
  const { aiSettings, setAISettings } = useOnboardingStore();
  const [errors, setErrors] = useState<Partial<Record<keyof AISettings, string>>>({});

  const zone = getThresholdZone(aiSettings.confidenceThreshold);

  const handleThresholdChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const value = parseInt(e.target.value, 10);
      if (!isNaN(value)) {
        setAISettings({ confidenceThreshold: value });
        setErrors((prev) => {
          if (!prev.confidenceThreshold) return prev;
          const next = { ...prev };
          delete next.confidenceThreshold;
          return next;
        });
      }
    },
    [setAISettings],
  );

  const handleToggleDisputes = useCallback(
    (checked: boolean) => {
      setAISettings({ allowDisputes: checked });
    },
    [setAISettings],
  );

  const handleToggleAutoGenerate = useCallback(
    (checked: boolean) => {
      setAISettings({ autoGenerateDocuments: checked });
    },
    [setAISettings],
  );

  const handleContinue = useCallback(() => {
    const result = aiSettingsSchema.safeParse(aiSettings);
    if (!result.success) {
      const fieldErrors: Partial<Record<keyof AISettings, string>> = {};
      for (const issue of result.error.issues) {
        const field = issue.path[0] as keyof AISettings;
        if (!fieldErrors[field]) {
          fieldErrors[field] = issue.message;
        }
      }
      setErrors(fieldErrors);
      return;
    }

    setErrors({});
    onNext();
  }, [aiSettings, onNext]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-brand-primary/10">
          <Brain className="h-6 w-6 text-brand-primary" />
        </div>
        <div>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            AI Settings
          </h2>
          <p className="text-sm text-text-secondary">
            Configure how the AI assistant operates in your workspace
          </p>
        </div>
      </div>

      {/* Confidence Threshold Slider */}
      <div className="rounded-xl border border-border bg-card/50 p-5">
        <FormField label="AI Confidence Threshold" required className="space-y-4">
          <div className="flex items-center gap-4">
            {/* Current value display */}
            <div className="flex items-baseline gap-1">
              <span
                className={cn(
                  "font-display text-4xl font-bold tabular-nums",
                  getZoneColor(zone),
                )}
              >
                {aiSettings.confidenceThreshold}
              </span>
              <span className="text-lg text-text-secondary">%</span>
            </div>

            {/* Zone indicator */}
            <div
              className={cn(
                "rounded-full px-3 py-1 text-xs font-medium",
                zone === "green" && "bg-brand-success/15 text-brand-success",
                zone === "yellow" && "bg-brand-warning/15 text-brand-warning",
                zone === "red" && "bg-brand-error/15 text-brand-error",
              )}
            >
              {zone === "green" ? "High" : zone === "yellow" ? "Moderate" : "Aggressive"}
            </div>
          </div>

          {/* Slider */}
          <div className="space-y-2">
            {/* Zone background bar */}
            <div className="relative h-2 w-full rounded-full bg-brand-slate">
              <div
                className="absolute left-0 top-0 h-full rounded-full bg-brand-error"
                style={{ width: "20%" }}
                aria-hidden="true"
              />
              <div
                className="absolute top-0 h-full rounded-full bg-brand-warning"
                style={{ left: "20%", width: "20%" }}
                aria-hidden="true"
              />
              <div
                className="absolute top-0 h-full rounded-full bg-brand-success"
                style={{ left: "40%", width: "60%" }}
                aria-hidden="true"
              />
            </div>

            <input
              type="range"
              min={50}
              max={99}
              value={aiSettings.confidenceThreshold}
              onChange={handleThresholdChange}
              className="slider-thumb w-full cursor-pointer appearance-none bg-transparent [&::-moz-range-thumb]:h-5 [&::-moz-range-thumb]:w-5 [&::-moz-range-thumb]:rounded-full [&::-moz-range-thumb]:border-2 [&::-moz-range-thumb]:border-brand-primary [&::-moz-range-thumb]:bg-brand-primary [&::-webkit-slider-thumb]:h-5 [&::-webkit-slider-thumb]:w-5 [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:border-2 [&::-webkit-slider-thumb]:border-brand-primary [&::-webkit-slider-thumb]:bg-brand-primary"
              aria-label="Confidence threshold percentage"
              aria-valuemin={50}
              aria-valuemax={99}
              aria-valuenow={aiSettings.confidenceThreshold}
              aria-valuetext={`${aiSettings.confidenceThreshold}%`}
            />

            {/* Scale labels */}
            <div className="flex justify-between text-xs text-text-tertiary">
              <span>50%</span>
              <span>60%</span>
              <span>70%</span>
              <span>80%</span>
              <span>90%</span>
              <span>99%</span>
            </div>
          </div>

          {/* Zone description */}
          <div className="flex items-start gap-2 rounded-lg bg-brand-slate/50 p-3">
            <Info className="mt-0.5 h-4 w-4 shrink-0 text-text-tertiary" />
            <p className={cn("text-xs", getZoneColor(zone))}>{getZoneLabel(zone)}</p>
          </div>

          {/* Zone legend */}
          <div className="flex gap-4 text-xs text-text-tertiary">
            <div className="flex items-center gap-1.5">
              <span
                className="h-2 w-2 rounded-full bg-brand-success"
                aria-hidden="true"
              />
              <span>80–99% High</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span
                className="h-2 w-2 rounded-full bg-brand-warning"
                aria-hidden="true"
              />
              <span>60–79% Moderate</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="h-2 w-2 rounded-full bg-brand-error" aria-hidden="true" />
              <span>50–59% Aggressive</span>
            </div>
          </div>

          {errors.confidenceThreshold && (
            <p className="text-xs text-brand-error" role="alert">
              {errors.confidenceThreshold}
            </p>
          )}
        </FormField>
      </div>

      {/* Toggle switches */}
      <div className="space-y-4">
        <Switch
          id="ai-allow-disputes"
          checked={aiSettings.allowDisputes}
          onCheckedChange={handleToggleDisputes}
          label="Allow employees to dispute disciplinary actions"
          description="When enabled, employees can submit a dispute for AI-recommended actions, triggering human review."
        />

        <Switch
          id="ai-auto-generate"
          checked={aiSettings.autoGenerateDocuments}
          onCheckedChange={handleToggleAutoGenerate}
          label="Auto-generate documents when confidence is high"
          description="When AI confidence exceeds your threshold, documents like warning letters will be drafted automatically."
        />
      </div>

      {/* Actions */}
      <div className="flex items-center justify-between pt-2">
        <Button type="button" variant="ghost" onClick={onPrev}>
          Back
        </Button>
        <Button type="button" size="lg" onClick={handleContinue}>
          Continue
        </Button>
      </div>
    </div>
  );
}
